accelerometer_noise_density: 0.001 # 0.224 0.1
gyroscope_noise_density: 0.000001 # 0.0128 0.1
accelerometer_random_walk: 0.001  # 0.043  0.0001
gyroscope_random_walk: 0.0001  # 0.0011  0.0001
integration_sigma: 0.626227 # 0.316227 TODO: ?

normalizeCamSize: 1.5               # Sets the size of the displayed camera (normalized with the scale obtained from IMU data).

# TODO:
#  ------------------- Used for planar robots -------------------
setting_weightZeroPriorDSOInitY: 5e09
setting_weightZeroPriorDSOInitX: 5e09
setting_forceNoKFTranslationThresh: 0.01

#init_transitionModel: 2 # mode 4 doesn't work; mode 1, 2 don't fix the scale; mode 5 causes tracking failure
#init_pgba_reinitScaleUncertaintyThresh: 1e6 # 1e6
#init_scalePriorAfterInit: 1.0 # This is a DEVIATION, not a prior scale value
#maxTimeBetweenInitFrames: 0.1 # Reset the visual initializer if this time has passed between the first and last frame.
#baToCoarseAccBiasVariance: 0.05
#baToCoarseGyrBiasVariance: 0.05

#maxSkipFramesVisualOnlyMode: 1      # This many frames can be skipped at a time while in visual-only mode.
#maxSkipFramesVisualInertial: 2      # This many frames can be skipped at a time while in visual-inertial mode.
#skipFramesVisualOnlyDelay: 30       # After visual initializer finished, wait this amount of frames before switching to the visualOnly threshold. This is useful because during the first frames the system might be less stable than later.
#minQueueSizeForSkipping: 2          # Don't skip frames if the image queue is smaller than this
#init_pgba_skipFirstKFs: 1 # 4 seasons: 0 (remove)
#init_requestFullResetNormalizedErrorThreshold: 0.1 #  4 seasons: remove (???)  # If the error after the CoarseIMUInit is larger than this we assume the visual system failed and reset the full system.
# With the following settings, VIO is initialized a bit earlier (default values in comment behind it).
# To adjust these settings you can read the CoarseIMUInit scale and variance printed out by the system and see with which variance it typically outputs a reasonable scale.

#init_coarseScaleUncertaintyThresh: 5 # 4 seasons:  1.0
#init_pgba_scaleUncertaintyThresh: 5 # 4 seasons: 1.0
#init_pgba_reinitScaleUncertaintyThresh: 0.3 # 4 seasons:  0.5
# If you are sure that no clouds will cover a large part of the image you can include points with any depth by enabling the following line.
#setting_minIdepth: 0.0

# ------------------- New ones -------------------

#setting_scaleFixTH: 0.01  # When the scale changes less than this threshold over generalScaleIntervalSize optimizations we fix it. 0.005 or 0.007 are good values for it.
#setting_visualOnlyAfterScaleFixing: 0 # Use the visual only system after scale has been fixed, which can be useful for debugging (only makes sense together with setting_scaleFixTH). 1 means that also the gtsamIntegration is not used anymore, while 2 means that the gtsamIntegration is still used with IMUExtension removed.

#setting_weightDSOToGTSAM: 0.001 # Originally 1.0 / 60000

#setting_optScaleBA: 0
