minNumPointsToSend: 100
useRANSAC: false

# RANSAC parameters
distanceThreshold: 0.01 # 0.01
probability: 0.99  # NOT IN USE
maxIterations: 1000  # NOT IN USE

# RadiusOutlierRemoval settings
minNeighborsInRadius: 8
radiusSearch: 0.2

# StatisticalOutlierRemoval settings
meanK: 10
stddevMulThresh: 0.01